name: Metrics isocalendar

on:
  schedule:
    - cron: "37 5 * * *"   # daily
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/metrics.yml"

permissions:
  contents: write

jobs:
  isocalendar:
    runs-on: ubuntu-latest
    steps:
      - name: Isometric commit calendar
        uses: lowlighter/metrics@latest
        with:
          user: Shehabov
          token: ${{ secrets.METRICS_TOKEN || secrets.GITHUB_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          filename: metrics.isocalendar.svg
          base: ""
          config_timezone: Europe/Istanbul
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
